sudo: required
language: python
git:
  depth: 3
  lfs_skip_smudge: true
  submodules: false
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - nightly
  - pypy
  # - pypy3
matrix:
  include:
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7
      python: 2.7
      before_install: pyenv install $TRAVIS_PYTHON_VERSION
  allow_failures:
    - os: osx
    - python: 2.6
    - python: 3.7-dev
    - python: nightly
    - python: pypy
    # - python: pypy3
  fast_finish: true
cache: pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install pandoc
  # - sudo apt-get -qq install python-pycurl
install:
  - pip install -U setuptools
  - pip install -U tox
  - pip install pypandoc
  - pip install requests
  # - pip install scrutinizer-ocular
  - pip install tox-travis
  # - pip install travis-bump-version
script: tox --skip-missing-interpreters
after_script:
  - tox -e dups
  - tox -e pylint -- -E
# after_success: ocular
before_deploy: test $TRAVIS_TEST_RESULT -eq 0
deploy:
  - provider: pypi
    user:
      secure: "mluJyTHPamuHJoPV/tA4fbmJ6t89lCKyIGlc32EnZqUWklu138xGGBtQhGYxcTKzh6L4lhDFpGVyYJeSvtOqsfhDHnElnzA89zplqDOR//Y5tayps1q2E8KI9zkNSL9Eq3G6cONVZCF3AbFxIdP3g2zNA2hcC3OoaXjM8N7270Y="
    password:
      secure: "YdhzNRg2x5eoLmjpoer2WmbzHy5sSC3K3/1v1cAVv2DSwuFas13Bp4S4kMhz0eXU+yqNvM16tDM488PY6Kjtw1663A4oVNANA71bUc61yWUqN1G9NYNiA9HM4GAG1wjUFjDUKcArX7d9I5Pw14T/AfP9A8AmkDgt3tNz45jKg9k="
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    on:
      python: 3.5
      tags: true
  # - provider: releases
    # api-key: "LDbvOV6EIV2itKUOSQE24RctMJTj7trF8eRQIMQJFa50W/fT03HpHiRVzhddUo4UadzAy5XNm5fRZY5AMNOomQk023mHwTUuPIhQDLVl1Esati7OZpekhKE1v4+sbLfVvvv+rRuDfcn+qjiZ358UU6D4SuZ4zClu6hUxnt0Qc70="
    # file_glob: true
    # file: dist/*
    # skip_cleanup: true
    # on:
      # python: 3.5
      # tags: true
# after_deploy: travis-bump-version --api-token "LDbvOV6EIV2itKUOSQE24RctMJTj7trF8eRQIMQJFa50W/fT03HpHiRVzhddUo4UadzAy5XNm5fRZY5AMNOomQk023mHwTUuPIhQDLVl1Esati7OZpekhKE1v4+sbLfVvvv+rRuDfcn+qjiZ358UU6D4SuZ4zClu6hUxnt0Qc70=" --repo $TRAVIS_REPO_SLUG VERSION
notifications:
  webhooks:
    urls:
      - secure: "cRnsy5ijZCyPJXIo9LoDaztpXcBr7VF3SjYRib1HHEE/LVn27hFnwLDDlL7R8FCpRdQOYXbkXNsY5ja62WIZttalzsd2RraApY+XH9QvSGGq6QNjoX593kMQ45PyqGpf3vrT9XwT5AXnw/WIg4umn7DBPsMX/aQtlNvvVlbI/6s="
    on_success: change
    on_failure: always
    on_start: never
